### ISSUE TITLE
Image mistake in article 2016/08-10--json-web-tokens-vs-session-cookies

### ISSUE THREAD

**Issue by bastilimbach** [ponyfoo/articles#4]
I think the last arrow (6. Sends response to the client.) of this image: https://camo.githubusercontent.com/04b3af16bd21592613613f8fa3540e5cc16b1567/68747470733a2f2f692e696d6775722e636f6d2f30665a313372442e706e67 points in the wrong direction. I didn't create a PR because I don't know, how you handle your image hosting. 

BTW, great article! 👍

**Comment by bevacqua** [comment]
It is, but sadly I didn't write this article, it was a guest post. If you want you can upload a fixed image to imgur and submit a PR
